In [1]:
from keras.datasets import mnist
import numpy as np

(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Se obtiene una muestra con igual número de: cincos vs no cincos
# para el conjunto de entrenamiento y el de test
idx_y_train_5 = np.where(y_train == 5)[0]
idx_y_train_n5 = np.where(y_train != 5)[0]
idx_y_train_n5 = np.random.choice(idx_y_train_n5, idx_y_train_5.shape[0], replace=False)

idx_y_train = np.concatenate([idx_y_train_5, idx_y_train_n5])
np.random.shuffle(idx_y_train)

x_train = x_train[idx_y_train]
y_train = y_train[idx_y_train]
print(x_train.shape)

idx_y_test_5 = np.where(y_test == 5)[0]
idx_y_test_n5 = np.where(y_test != 5)[0]
idx_y_test_n5 = np.random.choice(idx_y_test_n5, idx_y_test_5.shape[0], replace=False)

idx_y_test = np.concatenate([idx_y_test_5, idx_y_test_n5])
np.random.shuffle(idx_y_test)

x_test = x_test[idx_y_test]
y_test = y_test[idx_y_test]
print(x_test.shape)

y_train_binary = (y_train == 5).astype(int)
y_test_binary = (y_test == 5).astype(int)

2024-02-14 02:27:17.179123: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-14 02:27:17.179344: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-14 02:27:17.369654: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


11490434/11490434 [==============================] - 0s 0us/step
(10842, 28, 28)
(1784, 28, 28)


# 1
`epochs`           = 4

`batch size`       = 2000

`validation split` = 0.9

In [2]:
from keras.models import Sequential
from keras.layers import Flatten, Dense
from keras.metrics import F1Score

model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(1)
])

print(model.summary())

model.compile(loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train_binary, epochs=4, batch_size=2000, validation_split=0.9)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/4
1/1 [==============================] - 1s 843ms/step - loss: 7.9268 - accuracy: 0.4797 - val_loss: 7.6162 - val_accuracy: 0.5006
Epoch 2/4
1/1 [==============================] - 0s 57ms/step - loss: 7.9491 - accuracy: 0.4788 - val_loss: 7.6162 - val_accuracy: 0.5006
Epoch 3/4
1/1 [==============================] - 0s 44ms/step - loss: 7.9491 - accuracy: 0.4788 - val_loss: 7.6162 - val_accuracy: 0.5006
Ep

In [3]:
from sklearn.metrics import confusion_matrix, \
precision_score, recall_score,f1_score

y_pred = (model.predict(x_test) >= 0.5).astype(int)[:,0]
conf_matrix = confusion_matrix(y_test_binary, y_pred)
print("Matriz de confusión:")
print(conf_matrix)

precision = precision_score(y_test_binary, y_pred)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[ 12 880]
 [  5 887]]
Precision_1: 0.5019807583474816
Recall_1: 0.9943946188340808
F1-score_1: 0.6671681083113952
Precision_0: 0.7058823529411765
Recall_0: 0.013452914798206279
F1-score_0: 0.026402640264026403


# 2
`epochs`           = 20

`batch size`       = 2000

`validation split` = 0.9

In [4]:
model_1 = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(1)
])

print(model_1.summary())

model_1.compile(loss='binary_crossentropy', metrics=['accuracy'])
model_1.fit(x_train, y_train_binary, epochs=20, batch_size=2000, validation_split=0.9)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/20
1/1 [==============================] - 1s 666ms/step - loss: 8.2693 - accuracy: 0.4585 - val_loss: 7.8127 - val_accuracy: 0.4871
Epoch 2/20
1/1 [==============================] - 0s 49ms/step - loss: 7.9511 - accuracy: 0.4760 - val_loss: 7.5540 - val_accuracy: 0.5042
Epoch 3/20
1/1 [==============================] - 0s 48ms/step - loss: 7.8266 - accuracy: 0.4871 - val_loss: 7.5180 - val_accuracy: 0.50

In [5]:
y_pred_1 = (model_1.predict(x_test) >= 0.5).astype(int)[:,0]
conf_matrix = confusion_matrix(y_test_binary, y_pred_1)
print("Matriz de confusión:")
print(conf_matrix)

precision = precision_score(y_test_binary, y_pred_1)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred_1)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred_1)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred_1, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred_1, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred_1, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 2ms/step
Matriz de confusión:
[[ 33 859]
 [ 46 846]]
Precision_1: 0.4961876832844575
Recall_1: 0.9484304932735426
F1-score_1: 0.6515209857527917
Precision_0: 0.4177215189873418
Recall_0: 0.03699551569506727
F1-score_0: 0.06797116374871268


# 3
`epochs`           = 4

`batch size`       = 2

`validation split` = 0.9

In [6]:
model_2 = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(1)
])

print(model_2.summary())

model_2.compile(loss='binary_crossentropy', metrics=['accuracy'])
model_2.fit(x_train, y_train_binary, epochs=4, batch_size=2, validation_split=0.9)

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_2 (Dense)             (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/4
542/542 [==============================] - 7s 13ms/step - loss: 4.7999 - accuracy: 0.6854 - val_loss: 5.5211 - val_accuracy: 0.6388
Epoch 2/4
542/542 [==============================] - 7s 12ms/step - loss: 4.5746 - accuracy: 0.7002 - val_loss: 5.3129 - val_accuracy: 0.6536
Epoch 3/4
542/542 [==============================] - 7s 12ms/step - loss: 5.0632 - accuracy: 0.6688 - val_loss: 4.9511 - val_accura

In [7]:
y_pred_2 = (model_2.predict(x_test) >= 0.5).astype(int)[:,0]
conf_matrix = confusion_matrix(y_test_binary, y_pred_2)
print("Matriz de confusión:")
print(conf_matrix)

precision = precision_score(y_test_binary, y_pred_2)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred_2)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred_2)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred_2, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred_2, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred_2, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 2ms/step
Matriz de confusión:
[[477 415]
 [105 787]]
Precision_1: 0.6547420965058236
Recall_1: 0.8822869955156951
F1-score_1: 0.7516714422158548
Precision_0: 0.8195876288659794
Recall_0: 0.5347533632286996
F1-score_0: 0.6472184531886025


# 4
`epochs`           = 4

`batch size`       = 2000

`validation split` = 0.01

In [8]:
model_3 = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(1)
])

print(model_3.summary())

model_3.compile(loss='binary_crossentropy', metrics=['accuracy'])
model_3.fit(x_train, y_train_binary, epochs=4, batch_size=2000, validation_split=0.01)

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_3 (Flatten)         (None, 784)               0         
                                                                 
 dense_3 (Dense)             (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/4
6/6 [==============================] - 1s 41ms/step - loss: 7.5824 - accuracy: 0.5027 - val_loss: 7.5595 - val_accuracy: 0.5046
Epoch 2/4
6/6 [==============================] - 0s 10ms/step - loss: 7.2490 - accuracy: 0.5240 - val_loss: 7.4228 - val_accuracy: 0.5138
Epoch 3/4
6/6 [==============================] - 0s 9ms/step - loss: 7.0015 - accuracy: 0.5403 - val_loss: 7.2797 - val_accuracy: 0.5229
Ep

In [9]:
y_pred_3 = (model_3.predict(x_test) >= 0.5).astype(int)[:,0]
conf_matrix = confusion_matrix(y_test_binary, y_pred_3)
print("Matriz de confusión:")
print(conf_matrix)

precision = precision_score(y_test_binary, y_pred_3)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred_3)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred_3)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred_3, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred_3, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred_3, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[123 769]
 [ 39 853]]
Precision_1: 0.5258939580764488
Recall_1: 0.9562780269058296
F1-score_1: 0.6785998408910103
Precision_0: 0.7592592592592593
Recall_0: 0.13789237668161436
F1-score_0: 0.23339658444022773


# 5 

In [10]:
model_4 = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(1)
])

print(model_4.summary())

model_4.compile(loss='binary_crossentropy', metrics=['accuracy'])
model_4.fit(x_train, y_train_binary, epochs=25, batch_size=64, validation_split=0.2)

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_4 (Flatten)         (None, 784)               0         
                                                                 
 dense_4 (Dense)             (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/25
136/136 [==============================] - 1s 4ms/step - loss: 7.1744 - accuracy: 0.5338 - val_loss: 5.9528 - val_accuracy: 0.6123
Epoch 2/25
136/136 [==============================] - 0s 3ms/step - loss: 5.1926 - accuracy: 0.6593 - val_loss: 5.0654 - val_accuracy: 0.6662
Epoch 3/25
136/136 [==============================] - 0s 3ms/step - loss: 4.2072 - accuracy: 0.7237 - val_loss: 3.4261 - val_accura

In [11]:
y_pred_4 = (model_4.predict(x_test) >= 0.5).astype(int)[:,0]
conf_matrix = confusion_matrix(y_test_binary, y_pred_4)
print("Matriz de confusión:")
print(conf_matrix)

precision = precision_score(y_test_binary, y_pred_4)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred_4)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred_4)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred_4, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred_4, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred_4, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[810  82]
 [100 792]]
Precision_1: 0.9061784897025171
Recall_1: 0.8878923766816144
F1-score_1: 0.8969422423556058
Precision_0: 0.8901098901098901
Recall_0: 0.9080717488789237
F1-score_0: 0.8990011098779134
