In [1]:
from keras.datasets import mnist
import numpy as np

(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Se obtiene una muestra con igual número de: cincos vs no cincos
# para el conjunto de entrenamiento y el de test
idx_y_train_5 = np.where(y_train == 5)[0]
idx_y_train_n5 = np.where(y_train != 5)[0]
idx_y_train_n5 = np.random.choice(idx_y_train_n5, idx_y_train_5.shape[0], replace=False)

idx_y_train = np.concatenate([idx_y_train_5, idx_y_train_n5])
np.random.shuffle(idx_y_train)

x_train = x_train[idx_y_train]
y_train = y_train[idx_y_train]
print(x_train.shape)

idx_y_test_5 = np.where(y_test == 5)[0]
idx_y_test_n5 = np.where(y_test != 5)[0]
idx_y_test_n5 = np.random.choice(idx_y_test_n5, idx_y_test_5.shape[0], replace=False)

idx_y_test = np.concatenate([idx_y_test_5, idx_y_test_n5])
np.random.shuffle(idx_y_test)

x_test = x_test[idx_y_test]
y_test = y_test[idx_y_test]
print(x_test.shape)

y_train_binary = (y_train == 5).astype(int)
y_test_binary = (y_test == 5).astype(int)

2024-02-14 02:21:50.482499: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-14 02:21:50.482629: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-14 02:21:50.658049: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


11490434/11490434 [==============================] - 1s 0us/step
(10842, 28, 28)
(1784, 28, 28)


# 1
`epochs`           = 4

`batch size`       = 2000

`validation split` = 0.9

In [2]:
from keras.models import Sequential
from keras.layers import Flatten, Dense
from keras.metrics import F1Score

model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(1)
])

print(model.summary())

model.compile(loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train_binary, epochs=4, batch_size=2000, validation_split=0.9)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/4
1/1 [==============================] - 1s 675ms/step - loss: 6.8946 - accuracy: 0.5507 - val_loss: 7.3794 - val_accuracy: 0.5202
Epoch 2/4
1/1 [==============================] - 0s 50ms/step - loss: 6.8489 - accuracy: 0.5554 - val_loss: 7.3919 - val_accuracy: 0.5193
Epoch 3/4
1/1 [==============================] - 0s 41ms/step - loss: 6.9789 - accuracy: 0.5470 - val_loss: 7.2942 - val_accuracy: 0.5256
Ep

In [3]:
from sklearn.metrics import confusion_matrix, \
precision_score, recall_score,f1_score

y_pred = (model.predict(x_test) >= 0.5).astype(int)[:,0]
conf_matrix = confusion_matrix(y_test_binary, y_pred)
print("Matriz de confusión:")
print(conf_matrix)

precision = precision_score(y_test_binary, y_pred)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[787 105]
 [765 127]]
Precision_1: 0.5474137931034483
Recall_1: 0.14237668161434977
F1-score_1: 0.22597864768683273
Precision_0: 0.5070876288659794
Recall_0: 0.8822869955156951
F1-score_0: 0.644026186579378


# 2
`epochs`           = 20

`batch size`       = 2000

`validation split` = 0.9

In [4]:
model_1 = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(1)
])

print(model_1.summary())

model_1.compile(loss='binary_crossentropy', metrics=['accuracy'])
model_1.fit(x_train, y_train_binary, epochs=20, batch_size=2000, validation_split=0.9)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/20
1/1 [==============================] - 1s 502ms/step - loss: 7.5965 - accuracy: 0.5055 - val_loss: 7.3991 - val_accuracy: 0.5185
Epoch 2/20
1/1 [==============================] - 0s 42ms/step - loss: 7.5277 - accuracy: 0.5101 - val_loss: 7.3385 - val_accuracy: 0.5226
Epoch 3/20
1/1 [==============================] - 0s 44ms/step - loss: 7.2965 - accuracy: 0.5240 - val_loss: 7.1004 - val_accuracy: 0.53

In [5]:
y_pred_1 = (model_1.predict(x_test) >= 0.5).astype(int)[:,0]
conf_matrix = confusion_matrix(y_test_binary, y_pred_1)
print("Matriz de confusión:")
print(conf_matrix)

precision = precision_score(y_test_binary, y_pred_1)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred_1)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred_1)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred_1, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred_1, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred_1, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[530 362]
 [500 392]]
Precision_1: 0.519893899204244
Recall_1: 0.43946188340807174
F1-score_1: 0.4763061968408262
Precision_0: 0.5145631067961165
Recall_0: 0.594170403587444
F1-score_0: 0.5515088449531738


# 3
`epochs`           = 4

`batch size`       = 2

`validation split` = 0.9

In [6]:
model_2 = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(1)
])

print(model_2.summary())

model_2.compile(loss='binary_crossentropy', metrics=['accuracy'])
model_2.fit(x_train, y_train_binary, epochs=4, batch_size=2, validation_split=0.9)

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_2 (Dense)             (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/4
542/542 [==============================] - 7s 12ms/step - loss: 5.8764 - accuracy: 0.6172 - val_loss: 5.3984 - val_accuracy: 0.6464
Epoch 2/4
542/542 [==============================] - 6s 12ms/step - loss: 5.5809 - accuracy: 0.6347 - val_loss: 6.2212 - val_accuracy: 0.5956
Epoch 3/4
542/542 [==============================] - 7s 13ms/step - loss: 5.7988 - accuracy: 0.6236 - val_loss: 5.9590 - val_accura

In [7]:
y_pred_2 = (model_2.predict(x_test) >= 0.5).astype(int)[:,0]
conf_matrix = confusion_matrix(y_test_binary, y_pred_2)
print("Matriz de confusión:")
print(conf_matrix)

precision = precision_score(y_test_binary, y_pred_2)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred_2)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred_2)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred_2, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred_2, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred_2, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[832  60]
 [620 272]]
Precision_1: 0.8192771084337349
Recall_1: 0.30493273542600896
F1-score_1: 0.4444444444444444
Precision_0: 0.5730027548209367
Recall_0: 0.9327354260089686
F1-score_0: 0.7098976109215018


# 4
`epochs`           = 4

`batch size`       = 2000

`validation split` = 0.01

In [8]:
model_3 = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(1)
])

print(model_3.summary())

model_3.compile(loss='binary_crossentropy', metrics=['accuracy'])
model_3.fit(x_train, y_train_binary, epochs=4, batch_size=2000, validation_split=0.01)

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_3 (Flatten)         (None, 784)               0         
                                                                 
 dense_3 (Dense)             (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/4
6/6 [==============================] - 1s 33ms/step - loss: 7.2137 - accuracy: 0.5270 - val_loss: 6.4371 - val_accuracy: 0.5780
Epoch 2/4
6/6 [==============================] - 0s 8ms/step - loss: 6.7662 - accuracy: 0.5553 - val_loss: 6.2972 - val_accuracy: 0.5872
Epoch 3/4
6/6 [==============================] - 0s 8ms/step - loss: 6.2489 - accuracy: 0.5899 - val_loss: 6.3197 - val_accuracy: 0.5872
Epo

In [9]:
y_pred_3 = (model_3.predict(x_test) >= 0.5).astype(int)[:,0]
conf_matrix = confusion_matrix(y_test_binary, y_pred_3)
print("Matriz de confusión:")
print(conf_matrix)

precision = precision_score(y_test_binary, y_pred_3)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred_3)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred_3)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred_3, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred_3, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred_3, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[486 406]
 [250 642]]
Precision_1: 0.6125954198473282
Recall_1: 0.7197309417040358
F1-score_1: 0.6618556701030928
Precision_0: 0.6603260869565217
Recall_0: 0.5448430493273543
F1-score_0: 0.5970515970515972


# 5 

In [10]:
model_4 = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(1)
])

print(model_4.summary())

model_4.compile(loss='binary_crossentropy', metrics=['accuracy'])
model_4.fit(x_train, y_train_binary, epochs=25, batch_size=64, validation_split=0.2)

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_4 (Flatten)         (None, 784)               0         
                                                                 
 dense_4 (Dense)             (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/25
136/136 [==============================] - 1s 3ms/step - loss: 6.1304 - accuracy: 0.5984 - val_loss: 5.3300 - val_accuracy: 0.6501
Epoch 2/25
136/136 [==============================] - 0s 3ms/step - loss: 4.7486 - accuracy: 0.6897 - val_loss: 4.6297 - val_accuracy: 0.6985
Epoch 3/25
136/136 [==============================] - 0s 2ms/step - loss: 4.1117 - accuracy: 0.7318 - val_loss: 3.8071 - val_accura