In [1]:
from keras.datasets import mnist
import numpy as np

(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Se obtiene una muestra con igual número de: cincos vs no cincos
# para el conjunto de entrenamiento y el de test
idx_y_train_5 = np.where(y_train == 5)[0]
idx_y_train_n5 = np.where(y_train != 5)[0]
idx_y_train_n5 = np.random.choice(idx_y_train_n5, idx_y_train_5.shape[0], replace=False)

idx_y_train = np.concatenate([idx_y_train_5, idx_y_train_n5])
np.random.shuffle(idx_y_train)

x_train = x_train[idx_y_train]
y_train = y_train[idx_y_train]
print(x_train.shape)

idx_y_test_5 = np.where(y_test == 5)[0]
idx_y_test_n5 = np.where(y_test != 5)[0]
idx_y_test_n5 = np.random.choice(idx_y_test_n5, idx_y_test_5.shape[0], replace=False)

idx_y_test = np.concatenate([idx_y_test_5, idx_y_test_n5])
np.random.shuffle(idx_y_test)

x_test = x_test[idx_y_test]
y_test = y_test[idx_y_test]
print(x_test.shape)

y_train_binary = (y_train == 5).astype(int)
y_test_binary = (y_test == 5).astype(int)

2024-02-14 19:45:18.135092: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-14 19:45:18.135273: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-14 19:45:18.258640: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


11490434/11490434 [==============================] - 1s 0us/step
(10842, 28, 28)
(1784, 28, 28)


In [2]:
from keras.models import Sequential
from keras.layers import Flatten, Dense
from keras.metrics import F1Score

def build_model(epochs, batch_size, val_split):
    model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(1)
    ])
    
    print(model.summary())
    model.compile(loss='binary_crossentropy', metrics=['accuracy'])
    model.fit(x_train, y_train_binary, epochs=epochs, 
              batch_size=batch_size, validation_split=val_split)
    
    return model

# 1
`epochs`           = 4

`batch size`       = 2000

`validation split` = 0.9

In [3]:
model_0 = build_model(4, 2000, 0.9)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/4
1/1 [==============================] - 1s 826ms/step - loss: 7.2305 - accuracy: 0.5304 - val_loss: 7.6125 - val_accuracy: 0.5058
Epoch 2/4
1/1 [==============================] - 0s 47ms/step - loss: 7.3957 - accuracy: 0.5203 - val_loss: 7.5593 - val_accuracy: 0.5084
Epoch 3/4
1/1 [==============================] - 0s 49ms/step - loss: 7.3942 - accuracy: 0.5203 - val_loss: 7.5593 - val_accuracy: 0.5084
Ep

In [4]:
from sklearn.metrics import confusion_matrix, accuracy_score, \
precision_score, recall_score,f1_score

y_pred_0 = (model_0.predict(x_test) >= 0.5).astype(int)[:,0]
conf_matrix = confusion_matrix(y_test_binary, y_pred_0)
print("Matriz de confusión:")
print(conf_matrix)

acc = accuracy_score(y_test_binary, y_pred_0)
print("Accuracy:", acc)
precision = precision_score(y_test_binary, y_pred_0)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred_0)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred_0)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred_0, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred_0, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred_0, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[836  56]
 [824  68]]
Accuracy: 0.5067264573991032
Precision_1: 0.5483870967741935
Recall_1: 0.07623318385650224
F1-score_1: 0.13385826771653545
Precision_0: 0.5036144578313253
Recall_0: 0.9372197309417041
F1-score_0: 0.6551724137931034


# 2
`epochs`           = 20

`batch size`       = 2000

`validation split` = 0.9

In [5]:
model_1 = build_model(20, 2000, 0.9)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/20
1/1 [==============================] - 1s 666ms/step - loss: 7.5533 - accuracy: 0.5101 - val_loss: 7.6176 - val_accuracy: 0.5053
Epoch 2/20
1/1 [==============================] - 0s 46ms/step - loss: 7.3972 - accuracy: 0.5203 - val_loss: 7.6176 - val_accuracy: 0.5053
Epoch 3/20
1/1 [==============================] - 0s 46ms/step - loss: 7.3972 - accuracy: 0.5203 - val_loss: 7.6176 - val_accuracy: 0.50

In [6]:
y_pred_1 = (model_1.predict(x_test) >= 0.5).astype(int)[:,0]
conf_matrix = confusion_matrix(y_test_binary, y_pred_1)
print("Matriz de confusión:")
print(conf_matrix)

acc = accuracy_score(y_test_binary, y_pred_1)
print("Accuracy:", acc)
precision = precision_score(y_test_binary, y_pred_1)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred_1)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred_1)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred_1, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred_1, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred_1, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[865  27]
 [845  47]]
Accuracy: 0.5112107623318386
Precision_1: 0.6351351351351351
Recall_1: 0.052690582959641255
F1-score_1: 0.09730848861283645
Precision_0: 0.5058479532163743
Recall_0: 0.9697309417040358
F1-score_0: 0.6648731744811683


# 3
`epochs`           = 4

`batch size`       = 2

`validation split` = 0.9

In [7]:
model_2 = build_model(4, 2, 0.9)

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_2 (Dense)             (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/4
542/542 [==============================] - 6s 11ms/step - loss: 8.0855 - accuracy: 0.4696 - val_loss: 7.5715 - val_accuracy: 0.5029
Epoch 2/4
542/542 [==============================] - 6s 11ms/step - loss: 7.7254 - accuracy: 0.4935 - val_loss: 7.5731 - val_accuracy: 0.5033
Epoch 3/4
542/542 [==============================] - 6s 11ms/step - loss: 7.7234 - accuracy: 0.4935 - val_loss: 7.5879 - val_accura

In [8]:
y_pred_2 = (model_2.predict(x_test) >= 0.5).astype(int)[:,0]
conf_matrix = confusion_matrix(y_test_binary, y_pred_2)
print("Matriz de confusión:")
print(conf_matrix)

acc = accuracy_score(y_test_binary, y_pred_2)
print("Accuracy:", acc)
precision = precision_score(y_test_binary, y_pred_2)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred_2)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred_2)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred_2, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred_2, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred_2, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[ 13 879]
 [  5 887]]
Accuracy: 0.5044843049327354
Precision_1: 0.5022650056625142
Recall_1: 0.9943946188340808
F1-score_1: 0.6674191121143717
Precision_0: 0.7222222222222222
Recall_0: 0.014573991031390135
F1-score_0: 0.02857142857142857


# 4
`epochs`           = 4

`batch size`       = 2000

`validation split` = 0.01

In [9]:
model_3 = build_model(4, 2000, 0.01)

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_3 (Flatten)         (None, 784)               0         
                                                                 
 dense_3 (Dense)             (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/4
6/6 [==============================] - 1s 41ms/step - loss: 6.9154 - accuracy: 0.5487 - val_loss: 6.7491 - val_accuracy: 0.5596
Epoch 2/4
6/6 [==============================] - 0s 9ms/step - loss: 6.1173 - accuracy: 0.6001 - val_loss: 6.4669 - val_accuracy: 0.5780
Epoch 3/4
6/6 [==============================] - 0s 9ms/step - loss: 5.8217 - accuracy: 0.6187 - val_loss: 6.1766 - val_accuracy: 0.5963
Epo

In [10]:
y_pred_3 = (model_3.predict(x_test) >= 0.5).astype(int)[:,0]
conf_matrix = confusion_matrix(y_test_binary, y_pred_3)
print("Matriz de confusión:")
print(conf_matrix)

acc = accuracy_score(y_test_binary, y_pred_3)
print("Accuracy:", acc)
precision = precision_score(y_test_binary, y_pred_3)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred_3)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred_3)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred_3, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred_3, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred_3, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[430 462]
 [161 731]]
Accuracy: 0.6507847533632287
Precision_1: 0.6127409891031014
Recall_1: 0.8195067264573991
F1-score_1: 0.701199040767386
Precision_0: 0.727580372250423
Recall_0: 0.4820627802690583
F1-score_0: 0.5799055967633177


# 5 

In [11]:
model_4 = build_model(25, 64, 0.2)

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_4 (Flatten)         (None, 784)               0         
                                                                 
 dense_4 (Dense)             (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/25
136/136 [==============================] - 1s 3ms/step - loss: 8.0499 - accuracy: 0.4737 - val_loss: 7.7618 - val_accuracy: 0.4938
Epoch 2/25
136/136 [==============================] - 0s 2ms/step - loss: 6.7391 - accuracy: 0.5608 - val_loss: 6.9185 - val_accuracy: 0.5482
Epoch 3/25
136/136 [==============================] - 0s 2ms/step - loss: 5.7219 - accuracy: 0.6255 - val_loss: 5.3408 - val_accura

In [12]:
y_pred_4 = (model_4.predict(x_test) >= 0.5).astype(int)[:,0]
conf_matrix = confusion_matrix(y_test_binary, y_pred_4)
print("Matriz de confusión:")
print(conf_matrix)

acc = accuracy_score(y_test_binary, y_pred_4)
print("Accuracy:", acc)
precision = precision_score(y_test_binary, y_pred_4)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred_4)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred_4)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred_4, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred_4, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred_4, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[752 140]
 [ 86 806]]
Accuracy: 0.8733183856502242
Precision_1: 0.8520084566596194
Recall_1: 0.9035874439461884
F1-score_1: 0.8770402611534277
Precision_0: 0.8973747016706444
Recall_0: 0.8430493273542601
F1-score_0: 0.869364161849711
